server:
  port: 9999
  tomcat:
    max-connections: 30000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ku1?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ip: localhost

# 支付宝沙箱配置
alipay:
  app-id: "9021000162612447"
  private-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCoBF/A0co8HaXBE8+pHU6PPTI15kekOmX422dCWmVNM29Qm0c+l3fu4bN9u9QOpH8/WeP2YXrpYez7yE5vse060mL65uEbS0aohMH9L92RR15weTssaN+VjkBiRd1STqhcOnWz9jRF0ep5PJmbKJM19qtV9f8hSnkEpf53v9l3KgENlAX6K6/CVLZO3SMXCn686UAsHDLzg/cKL0qSR632i9vv5S2DbKSdj62pAkROvARBkdWB6vlpBYS+0GLMkAmrT7Ogrd/xEkotU424E2y62iGyl3K8tBK8A5XjVPVfunBPAhmlP6y1CQ+Xakwh8MckIBK8wbrQBXWFWWSmCJKnAgMBAAECggEAN8Kr3JxDV8wnFHr0shVt2w/eOBEiuZg/+2UlUdoaQJLPYJsH+/fc78SsAxBxAiMJsAavJzeWyRmcwrrpfRw5tQnZm5dAIgTLgGX+034tNGfRKdayEr0DZuj86SByoTxFl8Y3BfCxzHIsNOwttlay9HfWyQKJF41VuHs2hpt/GpKmd+LOVQ1OP1LrBVnPBkjKeLrf/519O7HdBQCcA1eISfOBYNDv6kfU7Gqxp85HhE5PclAVQK7wid3yjBAr814DKWVRAQltBAIWpwHlJvTpabzDXDbXwPNCxNiiXBXOkW6tAEbDNxIJZVcb3DKC564s6JF+JYTBJBYI0TN3CaXFQQKBgQDRrVNcIL1iiZoqE+3hF6sb0eQj8CPMci4oq7YjPKr2rNUboAvshclILnMHg9BbPqKSdDeVg7UrAZtlkKoykZiZwKzZmoS8cLiXA0Wn7lVKiYcZRwLPNi4bWJXTBvi5RCfRJau7AmyqhzUdoA8QYPtuHa1R5ybhNGTlmc7YgM2W9wKBgQDNIuRJ/sUaS/Kut2xP2Fy9F+FDZoipflzC9n2cSLUOZdbP/qUBsBNJ0uQV1YfjTe+ZQ0jJa9UgM8IrPm4gpmTeCF+TqLRSDGmcI0DUi5eeLhEOXYJbv6jCuCfkMVJgtQ/LT9yjZOD2I8rh79uYvMUueoL9oDmo6oDxULvbM6F0QKBgH9OXFGQc0xTva2UohbL1xEyE/GaCTJFlS8OaqzkVe0lrNJ0DylRZY+U3DSQ3L25vt1rAKCf8iylciNtfVjsu5mGuav5PGRpkDnoO6+lblWuQL+hNNx4ye/Cjl0tW3CpJ/+9fpIx+6ZiJ2bQWrUYHTCThjs3PIz50dTx2Pvs4GarAoGAfmb0or/RNl38B/lYZ8K1Sn9YaIU0KAt7xS9VVGzsWDdQk5K91f6++guvnTajw/dhlPlxeenbusdQS3lCuzYGaf9JLCpKW4kPxw5tZdF67w2WBbwehruVPmQSe2BaoOxz2qYIBY9FiaWkut7/z4Y7YNcaZ9qyHOxWc9JWZ2/1ZjECgYEAqcazFQPgS9Rr9hpsxcw1evYbqUPGSx+ETlT8WldsuT+T9yVSQ4sJrGB+2TUCQskVhL5loDhTzt8Jhho/Wqzo2Zqfhy9kbv8ux4mLJ5JNcsA74hwgk8yjsEuf8r5aysOLn82WLnwncDi0Cc/QW2neJkkYp3KguiVHzc7mdrP9o4Q="
  alipay-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsj6z4xx87ppu2qavFvkTnJcyWsm4lScdeZZs2MRZI/nRsOOAWZzGeao2PLcBeI0tublN0EAxYkhO3St1gW2aRuFOjqn08JpBhp/kBhI/gi4glO5xJ2CZV2kaKo8AaNl7zgHxhJ/Wuo9zO7ddAB4OVVa2Gs7UZg966/KZhsMOlOW/UKtOajVgKjGNyxrMkdLLBupxLcWnSagMfKexGOYHxc6a8UT8sYI8tBmUJxyludlQzD05WYw7+zHuCZv4fyJh9gEe7D+pH1/Y+vfZiUfOWmjpU/WTDHMkutGW8swY/PtTO/LoqMBpDAB5fzpKoaqKiOn5vymxaCqiqTMXyBWJNwIDAQAB"
  gateway-url: "https://openapi-sandbox.dl.alipaydev.com/gateway.do"
  sign-type: "RSA2"
  charset: "utf-8"
  format: "json"
  notify-url: "http://localhost:9999/orders/alipay/notify"
  return-url: "http://localhost:8085/front/orders"
