server:
  port: 9999
  tomcat:
    max-connections: 30000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ku1?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  transaction:
    default-timeout: 3600

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

ip: localhost
# 支付宝沙箱配置
alipay:
  app-id: "9021000162612447"
  private-key: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCMBtKELutbniMGDc38EmZEsgKEyJfacmAegbaHiF9Mr97hMrgbF8cN7wFLN6Hk8aemKXFQmFtCNwyPsZDRv6bNSV92DLKU15xa2YkQreJCbk/bS7fBSkO6VcHzbQih2kEgIyv/7vvTDSVhHRBwvLcZtobE1Cas8TnwdI6hpFQxAnO7YDEvL4gb7py5ZOa3VK7X2VhZCebKTKhpomiR3y+vitpYAd1qHa/AOdCtpS3xny4T3QiUl6Pi3eJBjDHZPs2McmNm++Wuc+Md7jwTy4STOmGCMQtPp6QpqsA9oCICvPYiGzLqe+Dg4RMhjqgqlEGlgsHBfHrbAGeeMsYj128XAgMBAAECggEABX22/6v/WsZmxTQBYeMu037Pjnl3Sv+1OT0I9WOpqQ40hUxB3/4ctjUrLdHurVW0p1V0th5jZcNW4MOr1C3Z0q8P6UcyMZgK750cPOU0vDorM4RSnmfVJBd81Zju/7nZV/NJJG4wveQEFTzYijM8UuvPeSSAp8OF7CIF/dy92HYbOYGDYdflsaUL3kOfbCiFbm/bKPJhaBws45N516Il/44h60tKDU+xiwMavmNza5qKQwEthbjxGL2RHDs8+uY5AWWQmeCFpxyOygVIHIiiSp86ICn2zD8zvjrg4iqWmgjrDzR8Zv+ggrQ9kmooqIlPeNzIl3DbPnZ1HPlyCPjcAQKBgQDSMZM5fuBBnaFNro+H/x4Neb6s6KDfQFl3I6LYDnmoW0urtVPlwx0G83tVIKcu7Q9ZolxKOipIsz9dHgBlhhhuP5s/j9SF/cXI3J3J88XUW086sSJNWiCykpE/+8xd0HchKpyKM84/fREgweTV0WVZbPeVrilwVICwPqxAzQwYFwKBgQCqirkn9ufs46HTyu8Zz4coJTKdz+Ie/4hPYXRdzOkNPFPBHt+jhVwEXxuLI/uf4ky0nP00Zu6Rze84QmQIRuCndNPA4f/GhmyRiAfqeTMHWjuQEP+0YBxcbf99wyy99VvWJltvlpnB1H88BT5VkPfryiY4mqalY3cxJ30Oj67BAQKBgQCUv8armrFDXjUnz0/98zomWTDqFpq6Q0TM/mggtGW+EhXEB0e/QswI/kgan0gQ+myxhyf+05jW6BsAX9nx/urNIrBQVA4XYNcWZaI4qA4pUREJvQ9EZHLdTMID4MLo5T1ZOFmdqDneTjjP0MeL1Wr+1RGFWMI0n2iO0Vt/ZFyZswKBgH4fN41RsPVk5uHtm2P4MRlEYSmKesy358Pk650PFG9AZSRWQ8f3sTRebc054DW+s0GDNFKTqO1VYgu2NapVWIEfChcETBcyhIogEtKZrV5Loe8KU0C/L1o/0wnb1HPrR26ZUVe2BaHuF+Z4bj/zhRXwmtGTtZhsddJ5RKgHJJMBAoGBALebXSCE/lL5yG2J1B5VwCsp7MolXJzFcfHbcT8DBboXywCCcP07um2iCDixbLkdm2LsKiDgU8e0/jD+u1KNufNCPYVFEt8wanl5jh/qvnlaR+Zt/dKdnSbiC0jqzbqYS88n5iMngSgtD9a5uInkDNp4a2rh2IDGmx9lTF5ipqNu"
  alipay-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsj6z4xx87ppu2qavFvkTnJcyWsm4lScdeZZs2MRZI/nRsOOAWZzGeao2PLcBeI0tublN0EAxYkhO3St1gW2aRuFOjqn08JpBhp/kBhI/gi4glO5xJ2CZV2kaKo8AaNl7zgHxhJ/Wuo9zO7ddAB4OVVa2Gs7UZg966/KZhsMOlOW/UKtOajVgKjGNyxrMkdLLBupxLcWnSagMfKexGOYHxc6a8UT8sYI8tBmUJxyludlQzD05WYw7+zHuCZv4fyJh9gEe7D+pH1/Y+vfZiUfOWmjpU/WTDHMkutGW8swY/PtTO/LoqMBpDAB5fzpKoaqKiOn5vymxaCqiqTMXyBWJNwIDAQAB"
  gateway-url: "https://openapi-sandbox.dl.alipaydev.com/gateway.do"
  sign-type: "RSA2"
  charset: "utf-8"
  format: "json"
  notify-url: "http://localhost:9999/orders/alipay/notify"
  return-url: "http://localhost:8085/front/orders"
